version: '3.4'

networks:
  dev:
    driver: bridge

services:
  dotnetbackend:
    image: docker.io/library/dotnetbackend
    labels:
      co.elastic.logs/module: YourServiceName
    depends_on:
      - "app_db"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=myuser;Password=mypassword;Server=app_db;Port=5432;Database=mydb;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 5290:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
    
volumes:
  app_data:

#